#a
zeiten = scan("~/Desktop/rPraktikum/daten/bearbzeit.dat")
# using xaxp = c(begin, end, block number )
hist(zeiten,breaks = seq(60,150,by = 10),xaxp= c(60,150,9),ylim = c(0,20),xlim = c(60,150),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Absolute Klassenhaeufigkeiten", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2")
minor.tick(ny = 5)
# modify the x axises
v1 = seq(60,150,by = 10)
v2 = as.character(v1)
axis(side = 1,
     at = v1,
     labels = v2,
     tck = -.05)

aDist.data = hist(zeiten, breaks = v1)
aDist.data$counts
aDist.data$density


hist(zeiten,breaks = seq(60,150,by = 10),xaxp= c(60,150,9),freq = FALSE, ylim = c(0,0.025),xlim = c(60,150),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Absolute Klassenhaeufigkeiten", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2")

# b fehlt
# should first use the xaxt = "n" option to block the x-axis tick label generated by the 
# hist function , then use the axis function to customize the label, otherwise, the two labels
# will overlap

# the outlook  change a lot in comparision with the former, which shows that histogram varies a lot accordinng to the interval
# division
hist(zeiten,breaks = seq(62,152,by = 10),ylim = c(0,20),xaxp = c(62,152,9),xlim = c(62,152),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Absolute Klassenhaeufigkeiten", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2")
hist(zeiten,breaks = seq(62,152,by = 10),ylim = c(0,20),xlim = c(62,152),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Absolute Klassenhaeufigkeiten", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2",xaxt = "n")

# modify the x axises
v1 = seq(62,152,by = 10)
v2 = as.character(v1)
axis(side = 1,
     at = v1,
     labels = v2,
     tck = -.05)


#c
breakInterval = c(60,80,90,100,seq(100,120,by = 5),130,150)
# how did the hist know that here is relative frequency
hist(zeiten,breaks = breakInterval,ylim = c(0,0.025),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Zugehoerige Hoehen", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2
     (Klasseneinteilung mit nicht-aequidistanten Klassen)")
naDist.data = hist(zeiten,breaks = breakInterval, plot = FALSE)

k1.rel = round(naDist.data$counts/length(zeiten), digits = 3)
k1.rel
naDist.data$counts
naDist.data$density
w1 = breakInterval
w2 = as.character(w1)
axis(side = 1,
     at = w1,
     labels = w2,
     tck = -.05)

#d
stem(zeiten)
stem(sort(zeiten))
