#a
zeiten = scan("~/Desktop/rPraktikum/daten/bearbzeit.dat")
# using xaxp = c(begin, end, block number )
hist(zeiten,breaks = seq(60,150,by = 10),xaxp= c(60,150,9),ylim = c(0,20),xlim = c(60,150),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Absolute Klassenhaeufigkeiten", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2")
minor.tick(ny = 5)
# modify the x axises
v1 = seq(60,150,by = 10)
v2 = as.character(v1)
axis(side = 1,
     at = v1,
     labels = v2,
     tck = -.05)

aDist.data = hist(zeiten, breaks = v1,plot = FALSE)
aDist.data$counts
aDist.data$density


hist(zeiten,breaks = seq(60,150,by = 10),xaxp= c(60,150,9),freq = FALSE, ylim = c(0,0.025),xlim = c(60,150),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Absolute Klassenhaeufigkeiten", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2")

# for the mietspiegel2015 data
miet = read.csv("~/Desktop/rPraktikum/daten/mietspiegel2015.csv",sep = " ",header = TRUE)
attach(miet)
miet.cut = cut(wfl,breaks=c(0,39,81,121,301),
               labels = c("to 38","39-80","81-120",">=121"),
                right=FALSE,dig.lab=3)
table(miet.cut)

# alternative: add a bin variable to the original data frame
miet.group <- miet %>%
        mutate( bin = cut(wfl,breaks=c(0,39,81,121,301),
            labels = c("to 38","39-80","81-120",">=121"),
            right=FALSE,dig.lab=3))
table(miet.group$bin)
par(las=1)
barplot(table(miet.cut),horiz=TRUE,xlim = c(0,2000))

miet.mittel = subset(miet, (wfl >= 80 & wfl <= 100)) $nm
stem(miet.mittel,scale = 2)
range(miet.mittel)


hist <- histogram(~nm | miet.cut,
                  breaks = seq(from = 0, to = 6000,by = 100),
                  xlab = list(label="net rent in euro",cex = 1.5),
                  ylab = list("percent",cex = 1.5),
                  col = "grey90",
                  type = "percent",
                  scales = list(cex = 1.5),
                  layout = c(1,4))
print(hist)

hist <- histogram(nm,breaks = seq(0,6000,200),scales = list(cex = 1.5),
                  xlab = list("net rent in euro",ex = 1.5),
                  ylab = list("density",cex = 1.5),
                  type = "density",
                panel = function(x,...) {
                       panel.histogram(x,...)
                 panel.densityplot(x,col="black",plot.points=FALSE)
     })
print(hist)
# b fehlt
# should first use the xaxt = "n" option to block the x-axis tick label generated by the 
# hist function , then use the axis function to customize the label, otherwise, the two labels
# will overlap

# the outlook  change a lot in comparision with the former, which shows that histogram varies a lot accordinng to the interval
# division
hist(zeiten,breaks = seq(62,152,by = 10),ylim = c(0,20),xaxp = c(62,152,9),xlim = c(62,152),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Absolute Klassenhaeufigkeiten", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2")
hist(zeiten,breaks = seq(62,152,by = 10),ylim = c(0,20),xlim = c(62,152),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Absolute Klassenhaeufigkeiten", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2",xaxt = "n")

# modify the x axises
# tck means the length of the streching ticks from the axis, if < 0, the extension is downward
v1 = seq(62,152,by = 10)
v2 = as.character(v1)
axis(side = 1,
     at = v1,
     labels = v2,
     tck = -0.05)


#c
breakInterval = c(60,80,90,100,seq(100,120,by = 5),130,150)
# how did the hist know that here is relative frequency
hist(zeiten,breaks = breakInterval,ylim = c(0,0.025),xlab = "Bearbeitungszeiten (in s)",
     ylab = "Zugehoerige Hoehen", main = "Histogramm der Bearbeitungszeiten zu den 
     Patienten- Daten aus Aufgabe P 2
     (Klasseneinteilung mit nicht-aequidistanten Klassen)", xaxt = "n")
naDist.data = hist(zeiten,breaks = breakInterval, plot = FALSE)

k1.rel = round(naDist.data$counts/length(zeiten), digits = 3)
k1.rel
naDist.data$counts
naDist.data$density
w1 = breakInterval
w2 = as.character(w1)
axis(side = 1,
     at = w1,
     labels = w2,
     tck = -.05)

#d
stem(zeiten)
stem(sort(zeiten))
